/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.dgzt.mundus.plugin.helperlines

import com.badlogic.gdx.Gdx
import com.mbrlabs.mundus.pluginapi.EventExtension
import com.mbrlabs.mundus.pluginapi.MenuExtension
import com.mbrlabs.mundus.pluginapi.PluginEventManager
import com.mbrlabs.mundus.pluginapi.ui.RootWidget
import org.pf4j.Extension
import org.pf4j.Plugin

class HelperLinesPlugin : Plugin() {

    companion object {
        const val RECTANGLE_RADIO_BUTTON_TEXT = "Rectangle"
        const val HEXAGON_RADIO_BUTTON_TEXT = "Hexagon"
    }

    @Extension
    class HelperLinesMenuExtension : MenuExtension {
        override fun getMenuName(): String = "Helper lines"
        override fun setupDialogRootWidget(root: RootWidget) {
            root.addRadioButtons(RECTANGLE_RADIO_BUTTON_TEXT, HEXAGON_RADIO_BUTTON_TEXT) { Gdx.app.log("", "Selected: $it") }
            root.addRow()
            root.addSpinner("Column", 2, 100, 2) { Gdx.app.log("", "Changed column to: $it") }
            root.addRow()
            root.addSpinner("Counter offset X", Int.MIN_VALUE, Int.MAX_VALUE, 0) { Gdx.app.log("", "Changed counter offset x: $it") }
            root.addRow()
            root.addSpinner("Counter offset Y", Int.MIN_VALUE, Int.MAX_VALUE, 0) { Gdx.app.log("", "Changed counter offset y: $it") }
        }

    }

    @Extension
    class HelperLinesEventExtension : EventExtension {

        override fun manageEvents(pluginEventManager: PluginEventManager) {
            pluginEventManager.registerEventListener(TerrainVerticesChangedEventListener())
        }

    }
}
