/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.dgzt.mundus.plugin.helperlines

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
